#!/usr/bin/env bash

dataset="dbpedia"
version="2015-10"
name="${dataset}_${version}"
url_prefix="http://downloads.dbpedia.org/${version}"
language="en"
url_prefix_path="${url_prefix}/core-i18n/${language}"
files="
	article_categories
	disambiguations
	infobox_properties
	instance_types
	mappingbased_objects
	redirects
	skos_categories
"
format="ttl"
compression='bz2'
additional_files="dbpedia_2015-10.nt"
