#!/usr/bin/env bash

# We reduced as much as possible the side of this dataset
# in order to make it tractable for graph processing.

dataset="dbpedia"
version="2015-10"
name="${dataset}_${version}"
url_prefix="http://downloads.dbpedia.org/${version}"
language="en"
url_prefix_path="${url_prefix}/core-i18n/${language}"
files="
	labels
	category_labels
	article_categories
	disambiguations
	instance_types
	mappingbased_literals
	mappingbased_objects
	redirects
	short_abstracts
"
format="ttl"
compression='bz2'
additional_files="dbpedia_2015-10.nt"
