#!/usr/bin/env bash

dataset="dbpedia"
version="2015-04"
name="${dataset}_${version}"
url_prefix="http://downloads.dbpedia.org/${version}"
language="en"
url_prefix_path="${url_prefix}/core-i18n/${language}"
files="
	instance-types
	mappingbased-properties
	labels
	short-abstracts
	article-categories
	category-labels
	skos-categories
	redirects
	disambiguations
"
format="nt"
compression='bz2'
additional_files="dbpedia_2015-04.nt"
