#!/bin/bash

url_prefix='http://downloads.dbpedia.org/2014'
url_prefix_path='http://downloads.dbpedia.org/2015-04/core-i18n/en/'
files="dbpedia_2015-04.nt instance-types_en.nt mappingbased-properties_en.nt labels_en.nt short-abstracts_en.nt article-categories_en.nt category-labels_en.nt skos-categories_en redirects_en.nt"
compression='bz2'
