#!/usr/bin/env bash

dataset="dbpedia"
version="2015-10"
name="${dataset}_${version}"
url_prefix="http://downloads.dbpedia.org/${version}"
language="en"
url_prefix_path="${url_prefix}/core-i18n/${language}"
files="
	labels
	short_abstracts
	article_categories
	category_labels
	skos_categories
	redirects
	disambiguations
"
format="ttl"
compression='bz2'
additional_files="dbpedia_2015-10.nt"
